service: msa-000-order-lambda
frameworkVersion: '>=4.1.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: select your region

functions:
  consumer:
    handler: index.consumer
    events:
      - sqs: YOUR_SQS_ARN
    timeout: 30
