service: msa-000-delivery-lambda
frameworkVersion: '>=4.1.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: select your region

functions:
  api:
    handler: index.consumer
    url: true
    timeout: 600
