service: msa-000-delivery-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2

functions:
  api:
    handler: index.consumer
    url: true
    timeout: 600
