service: delivery-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2

functions:
  api:
    handler: index.consumer
    events:
      - httpApi: '*'
    url: true

plugins:
  - serverless-lift
