service: msa-000-factory-lambda
frameworkVersion: '>=4.1.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: select your region

functions:
  api:
    handler: index.handler
    url: true
    timeout: 300
