service: nxtfactory-lambda
frameworkVersion: '>=4.1.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: YOUR_REGION_NAME

functions:
  api:
    handler: index.handler
    url: true
    timeout: 300
